name:                learning-haskell
version:             0.1.0.0
github:              "barudisshu/learning-haskell"
license:             BSD3
author:              "Galudisu"
maintainer:          "galudisu@gmail.com"
copyright:           "Apache"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/barudisshu/learning-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- mwc-random >= 0.14
- QuickCheck >= 2.11.1

library:
  source-dirs: src

executables:
  learning-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-haskell

tests:
  learning-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - learning-haskell
